<a href="https://colab.research.google.com/github/iamgchattejee/Fruit-Freshness-Prediction/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path
import os.path
import csv
import cv2
from sklearn.model_selection import train_test_split

import tensorflow as tf
import pandas as pd
df = pd.read_csv ('/content/drive/MyDrive/Colab Notebooks/Amloki-classified/rating.csv',usecols= ['Name','Average'])
from sklearn.metrics import r2_score
path = Path('/content/drive/MyDrive/Colab Notebooks/Amloki-classified/Combined')
l=[]  
d=[]
for img in os.listdir(path):
        temp = os.path.splitext(img)[0]
        img_path = os.path.join(path, img)
        label=df.loc[df['Name']==temp]["Average"]
        t=list(label)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (224, 224))
        d.append([new_arr,t[0]])
print(d)        

[[array([[198, 197, 195, ..., 157, 155, 155],
       [199, 200, 197, ..., 157, 155, 155],
       [195, 200, 196, ..., 154, 155, 158],
       ...,
       [248, 251, 247, ..., 181, 185, 185],
       [245, 248, 248, ..., 183, 184, 184],
       [245, 248, 248, ..., 184, 187, 187]], dtype=uint8), 8], [array([[192, 192, 189, ..., 169, 170, 171],
       [188, 192, 190, ..., 172, 171, 173],
       [193, 194, 194, ..., 173, 173, 174],
       ...,
       [238, 237, 239, ..., 205, 205, 201],
       [239, 241, 239, ..., 205, 203, 199],
       [240, 237, 237, ..., 206, 201, 199]], dtype=uint8), 8], [array([[166, 161, 162, ..., 172, 170, 167],
       [165, 163, 163, ..., 171, 173, 168],
       [163, 162, 161, ..., 173, 171, 171],
       ...,
       [224, 225, 226, ..., 214, 212, 213],
       [224, 224, 223, ..., 211, 213, 211],
       [224, 221, 225, ..., 211, 212, 209]], dtype=uint8), 7], [array([[197, 197, 197, ..., 178, 175, 176],
       [198, 199, 195, ..., 176, 176, 175],
       [198, 198, 198,

In [ ]:
X1 = []
Y1 = []

IMG_SIZE=224
for features, label in d:
    X1.append(features)
    Y1.append(label)

X1 = np.array(X1).reshape(-1,IMG_SIZE,IMG_SIZE,1)
Y1 = np.array(Y1)
print(X1)
print(Y1)


[[[[198]
   [197]
   [195]
   ...
   [157]
   [155]
   [155]]

  [[199]
   [200]
   [197]
   ...
   [157]
   [155]
   [155]]

  [[195]
   [200]
   [196]
   ...
   [154]
   [155]
   [158]]

  ...

  [[248]
   [251]
   [247]
   ...
   [181]
   [185]
   [185]]

  [[245]
   [248]
   [248]
   ...
   [183]
   [184]
   [184]]

  [[245]
   [248]
   [248]
   ...
   [184]
   [187]
   [187]]]


 [[[192]
   [192]
   [189]
   ...
   [169]
   [170]
   [171]]

  [[188]
   [192]
   [190]
   ...
   [172]
   [171]
   [173]]

  [[193]
   [194]
   [194]
   ...
   [173]
   [173]
   [174]]

  ...

  [[238]
   [237]
   [239]
   ...
   [205]
   [205]
   [201]]

  [[239]
   [241]
   [239]
   ...
   [205]
   [203]
   [199]]

  [[240]
   [237]
   [237]
   ...
   [206]
   [201]
   [199]]]


 [[[166]
   [161]
   [162]
   ...
   [172]
   [170]
   [167]]

  [[165]
   [163]
   [163]
   ...
   [171]
   [173]
   [168]]

  [[163]
   [162]
   [161]
   ...
   [173]
   [171]
   [171]]

  ...

  [[224]
   [225]
   [226]
   

In [ ]:
import pickle
pickle.dump(X1, open('/content/drive/MyDrive/X2.pkl', 'wb'))
pickle.dump(Y1, open('/content/drive/MyDrive/Y2.pkl', 'wb'))

In [ ]:
import pickle
pickle_in=open('/content/drive/MyDrive/X2.pkl', 'rb')
X=pickle.load(pickle_in)

pickle_in=open('/content/drive/MyDrive/Y2.pkl', 'rb')
y=pickle.load(pickle_in)
print(len(X))
print(len(y))

279
279


In [ ]:
from sklearn.model_selection import train_test_split
(trainX, testX, trainY, testY) = train_test_split(X, y,
	test_size=0.20, stratify=y, random_state=42)

print("Train Set Length: {} \nTest Set Length: {}".format(len(trainY), len(testY)))

print(trainY)
print(testY)

Train Set Length: 223 
Test Set Length: 56
[[7]
 [8]
 [7]
 [5]
 [8]
 [6]
 [8]
 [7]
 [3]
 [2]
 [5]
 [4]
 [8]
 [8]
 [3]
 [8]
 [8]
 [4]
 [7]
 [8]
 [8]
 [5]
 [8]
 [5]
 [6]
 [8]
 [7]
 [6]
 [6]
 [4]
 [8]
 [6]
 [6]
 [7]
 [7]
 [6]
 [8]
 [2]
 [4]
 [6]
 [5]
 [7]
 [8]
 [6]
 [8]
 [5]
 [8]
 [6]
 [4]
 [5]
 [5]
 [2]
 [8]
 [3]
 [3]
 [3]
 [5]
 [5]
 [8]
 [7]
 [5]
 [6]
 [8]
 [7]
 [7]
 [8]
 [3]
 [8]
 [7]
 [6]
 [6]
 [4]
 [5]
 [4]
 [7]
 [8]
 [2]
 [6]
 [5]
 [8]
 [8]
 [7]
 [7]
 [5]
 [8]
 [5]
 [7]
 [8]
 [6]
 [6]
 [8]
 [5]
 [6]
 [7]
 [7]
 [8]
 [7]
 [5]
 [6]
 [8]
 [5]
 [6]
 [6]
 [3]
 [6]
 [5]
 [3]
 [3]
 [8]
 [5]
 [3]
 [4]
 [4]
 [5]
 [3]
 [5]
 [3]
 [7]
 [8]
 [5]
 [8]
 [3]
 [8]
 [4]
 [7]
 [4]
 [8]
 [7]
 [4]
 [7]
 [7]
 [7]
 [7]
 [6]
 [4]
 [7]
 [7]
 [8]
 [8]
 [5]
 [8]
 [3]
 [3]
 [8]
 [5]
 [8]
 [7]
 [6]
 [7]
 [8]
 [3]
 [4]
 [7]
 [8]
 [3]
 [7]
 [4]
 [8]
 [3]
 [4]
 [4]
 [2]
 [7]
 [8]
 [5]
 [7]
 [4]
 [6]
 [4]
 [8]
 [8]
 [4]
 [3]
 [5]
 [7]
 [4]
 [7]
 [3]
 [7]
 [7]
 [8]
 [8]
 [8]
 [7]
 [7]
 [7]
 [8]
 [8]
 [4]
 [3]
 [7]
 [

In [ ]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K
from tensorflow.python.keras import regularizers
train_data_dir = 'data/train'
validation_data_dir = 'data/validation'
nb_train_samples = 251
nb_validation_samples = 28
epochs = 50
batch_size = 10

trainx=trainX/255.0

In [ ]:
model = Sequential()
model.add(Conv2D(64, (3,3), input_shape=trainx.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(3, 3)))

model.add(Conv2D(32, (3, 3), kernel_regularizer=regularizers.l2(l=0.10)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), kernel_regularizer=regularizers.l2(l=0.25)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(1))
model.add(Activation('linear'))
model.compile(
    optimizer='adam',
    loss='mse'
)    

history=model.fit(trainX,trainY,batch_size,epochs,validation_split=0.15)

Epoch 1/50
19/19 [==============================] - 15s 714ms/step - loss: 117417.8516 - val_loss: 27.5324
Epoch 2/50
19/19 [==============================] - 12s 615ms/step - loss: 31.6170 - val_loss: 18.0091
Epoch 3/50
19/19 [==============================] - 11s 599ms/step - loss: 16.4987 - val_loss: 14.1023
Epoch 4/50
19/19 [==============================] - 11s 602ms/step - loss: 15.9590 - val_loss: 15.2965
Epoch 5/50
19/19 [==============================] - 11s 601ms/step - loss: 15.2206 - val_loss: 14.1650
Epoch 6/50
19/19 [==============================] - 11s 598ms/step - loss: 14.7109 - val_loss: 13.9039
Epoch 7/50
19/19 [==============================] - 11s 597ms/step - loss: 14.7143 - val_loss: 13.9566
Epoch 8/50
19/19 [==============================] - 11s 601ms/step - loss: 14.9032 - val_loss: 13.8204
Epoch 9/50
19/19 [==============================] - 11s 600ms/step - loss: 14.2924 - val_loss: 14.2682
Epoch 10/50
19/19 [==============================] - 11s 600ms/step -

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import  roc_auc_score
import tensorflow as tf
import numpy as np
from tensorflow import keras

y_pred=model.predict(testX)
y_predict=np.ceil(y_pred)
y_predict=y_predict.astype(int)
print(y_predict)
print(testY)

[[7]
 [6]
 [3]
 [7]
 [7]
 [6]
 [4]
 [4]
 [7]
 [7]
 [5]
 [4]
 [7]
 [5]
 [7]
 [6]
 [7]
 [3]
 [4]
 [8]
 [7]
 [6]
 [4]
 [6]
 [5]
 [6]
 [5]
 [5]
 [7]
 [3]
 [7]
 [4]
 [6]
 [3]
 [8]
 [3]
 [4]
 [8]
 [7]
 [7]
 [7]
 [6]
 [4]
 [7]
 [6]
 [5]
 [7]
 [7]
 [8]
 [3]
 [7]
 [7]
 [7]
 [3]
 [6]
 [3]]
[[8]
 [6]
 [3]
 [7]
 [8]
 [7]
 [7]
 [5]
 [8]
 [8]
 [6]
 [4]
 [8]
 [6]
 [8]
 [6]
 [8]
 [4]
 [4]
 [8]
 [8]
 [7]
 [4]
 [5]
 [6]
 [7]
 [5]
 [5]
 [8]
 [5]
 [7]
 [5]
 [7]
 [4]
 [7]
 [2]
 [3]
 [8]
 [7]
 [8]
 [7]
 [7]
 [4]
 [8]
 [6]
 [7]
 [7]
 [7]
 [8]
 [3]
 [8]
 [6]
 [5]
 [3]
 [8]
 [3]]


In [ ]:
from sklearn.metrics import mean_squared_error

rms = mean_squared_error(testY, y_predict,squared=False)
print(rms)

0.9819805060619657
